### ISSUE TITLE
删除已经不存在的扫描任务会发现panic

### ISSUE THREAD

**Issue by Marcus9530** [actiontech/sqle#1205]
**SQLe Version**
UI Version: main 13665c5
Server Version: main-ee 00e48a44a8

1.创建一个扫描任务test1，此时该页面为标签页1，不关闭
2.然后在浏览器上再开一个标签页重新进入到扫描任务界面，可以看到test1任务，此时对该标签页不做任何操作
3.切换回到步骤1中的标签页里，对test1任务进行删除
4.回到切换到步骤2中的标签页里，可以看到test1任务，然后点击删除，出现未知错误
![VMVN2DLK8b](https://user-images.githubusercontent.com/54339501/207805039-1e57d902-ae63-477c-bae9-ce0418372c6d.jpg)

std日志出现panic
```bash
goroutine 3914 [running]:
net/http.(*conn).serve.func1(0xc0016e57c0)
	/usr/local/go/src/net/http/server.go:1805 +0x153
panic(0x18f2f80, 0xc0003c8c18)
	/usr/local/go/src/runtime/panic.go:971 +0x499
github.com/jinzhu/gorm.(*Scope).callCallbacks.func1(0xc000969a00)
	/universe/vendor/github.com/jinzhu/gorm/scope.go:865 +0xba
panic(0x18f2f80, 0xc0003c8c18)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
reflect.Value.MethodByName(0x0, 0x0, 0x0, 0x1b94e68, 0xc, 0xa95725, 0x1805160, 0x0)
	/usr/local/go/src/reflect/value.go:1354 +0x1f9
github.com/jinzhu/gorm.(*Scope).callMethod(0xc000969a00, 0x1b94e68, 0xc, 0x0, 0x0, 0x0)
	/universe/vendor/github.com/jinzhu/gorm/scope.go:438 +0x87
github.com/jinzhu/gorm.(*Scope).CallMethod(0xc000969a00, 0x1b94e68, 0xc)
	/universe/vendor/github.com/jinzhu/gorm/scope.go:252 +0x150
github.com/jinzhu/gorm.beforeDeleteCallback(0xc000969a00)
	/universe/vendor/github.com/jinzhu/gorm/callback_delete.go:24 +0x6d
github.com/jinzhu/gorm.(*Scope).callCallbacks(0xc000969a00, 0xc0004786c0, 0x5, 0x8, 0x0)
	/universe/vendor/github.com/jinzhu/gorm/scope.go:869 +0x83
github.com/jinzhu/gorm.(*DB).Delete(0xc0004721a0, 0x1805160, 0x0, 0x0, 0x0, 0x0, 0x1)
	/universe/vendor/github.com/jinzhu/gorm/main.go:489 +0x98
github.com/actiontech/sqle/sqle/model.(*Storage).Delete(0xc000010588, 0x1805160, 0x0, 0x7, 0xc0014a16e8)
	/universe/sqle/model/utils.go:348 +0x57
github.com/actiontech/sqle/sqle/api/controller/v1.DeleteAuditPlan(0x1e914f0, 0xc0016e5860, 0x0, 0xc000966500)
	/universe/sqle/api/controller/v1/audit_plan.go:391 +0x145
github.com/actiontech/sqle/sqle/api/middleware.licenseAdapter.func1.1(0x1e914f0, 0xc0016e5860, 0x5, 0xc001710b40)
	/universe/sqle/api/middleware/license_qa.go:13 +0x39
github.com/actiontech/sqle/sqle/api/middleware.VerifyUserIsDisabled.func1.1(0x1e914f0, 0xc0016e5860, 0x4, 0x1930360)
	/universe/sqle/api/middleware/verify_user.go:25 +0x1b2
github.com/labstack/echo/v4/middleware.JWTWithConfig.func1.1(0x1e914f0, 0xc0016e5860, 0x1b9709d, 0xd)
	/universe/vendor/github.com/labstack/echo/v4/middleware/jwt.go:238 +0x3ca
github.com/actiontech/sqle/sqle/api/middleware.JWTTokenAdapter.func1.1(0x1e914f0, 0xc0016e5860, 0x4, 0x4)
	/universe/sqle/api/middleware/jwt.go:26 +0xdc
github.com/labstack/echo/v4.(*Echo).add.func1(0x1e914f0, 0xc0016e5860, 0x3af5f40, 0x203000)
	/universe/vendor/github.com/labstack/echo/v4/echo.go:552 +0x62
github.com/labstack/echo/v4/middleware.LoggerWithConfig.func2.1(0x1e914f0, 0xc0016e5860, 0x0, 0x0)
	/universe/vendor/github.com/labstack/echo/v4/middleware/logger.go:117 +0x12c
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc000376fc0, 0x1e6f0e8, 0xc0017ac9a0, 0xc00084da00)
	/universe/vendor/github.com/labstack/echo/v4/echo.go:662 +0x2bc
net/http.serverHandler.ServeHTTP(0xc0017ac000, 0x1e6f0e8, 0xc0017ac9a0, 0xc00084da00)
	/usr/local/go/src/net/http/server.go:2868 +0xa3
net/http.(*conn).serve(0xc0016e57c0, 0x1e74b40, 0xc0014bb280)
	/usr/local/go/src/net/http/server.go:1933 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2994 +0x39b
```

**Comment by HuangWeiCen** [comment]
# 自测流程
完全按照测试的复现流程操作, 到最后一步删除不存在扫描任务时正确弹出提示
![image](https://user-images.githubusercontent.com/37464327/208634497-6b699877-d64d-4fd2-a2ee-f02c3b4d15aa.png)

**Comment by Marcus9530** [comment]
UI Version: main d121bfc
Server Version: main-ee 1f97752cb3
验证步骤：
1.创建一个扫描任务test1，此时该页面为标签页1，不关闭
2.然后在浏览器上再开一个标签页重新进入到扫描任务界面，可以看到test1任务，此时对该标签页不做任何操作
3.切换回到步骤1中的标签页里，对test1任务进行删除
4.回到切换到步骤2中的标签页里，可以看到test1任务，然后点击删除，提示扫描任务不存在。

<img width="1628" alt="image" src="https://user-images.githubusercontent.com/54339501/209620576-33f7bfab-3360-41ef-b6eb-d64072efd99b.png">
