### ISSUE TITLE
MySQL索引规则审核panic

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/sqle#1351]
复现版本: main 8f57cb6f80
复现步骤：
1. 开启规则审核 “建议选择可选性超过阈值字段作为索引”
2. 创建表：
```
create table foods(
 id bigint auto_increment primary key comment 'id',
 food_type int comment '食物类型',
 food_name varchar(100) comment '名称')
 comment '食物';
```
3. 创建工单，单击“审核”，页面报错：
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/36940986/222677800-91504208-d5df-422d-8c7f-24294d28c8ae.png">
4. std.log信息：

```
goroutine 231 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x7a
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/actiontech/sqle/sqle/server.hookAudit.func1()
	/usr/local/src/sqle/sqle/server/audit.go:95 +0x65
panic({0x1e3b0a0, 0x3eb0c80})
	/usr/local/go/src/runtime/panic.go:1047 +0x262
github.com/actiontech/sqle/sqle/driver/mysql/util.TableExistCol(0x0, {0xc0007a4aae, 0x9})
	/usr/local/src/sqle/sqle/driver/mysql/util/parser_helper.go:731 +0x57
github.com/actiontech/sqle/sqle/driver/mysql/session.(*Context).GetMaxIndexOptionForTable(0xc0004ff000, 0xc0002473f0, {0xc000525e30, 0x1, 0x1})
	/usr/local/src/sqle/sqle/driver/mysql/session/context.go:635 +0xaf6
github.com/actiontech/sqle/sqle/driver/mysql/rule.checkIndexOption(0xc00022ed80)
	/usr/local/src/sqle/sqle/driver/mysql/rule/rule.go:4295 +0x3f1
github.com/actiontech/sqle/sqle/driver/mysql.(*MysqlDriverImpl).Audit(0xc0012edf80, {0x229b430, 0xc0000440f0}, {0xc0007a4a80, 0x39})
	/usr/local/src/sqle/sqle/driver/mysql/mysql.go:330 +0x9e9
github.com/actiontech/sqle/sqle/server.hookAudit(0xc00017eee0, 0xc0011958c0, {0x22b1d60, 0xc0012edf80}, {0x2281d88, 0x3f42aa0})
	/usr/local/src/sqle/sqle/server/audit.go:142 +0x590
github.com/actiontech/sqle/sqle/server.audit(0xc00017eee0, 0xc0011958c0, {0x22b1d60, 0xc0012edf80})
	/usr/local/src/sqle/sqle/server/audit.go:78 +0x6f
github.com/actiontech/sqle/sqle/server.(*action).audit(0xc0011b6900)
	/usr/local/src/sqle/sqle/server/sqled.go:476 +0xaa
github.com/actiontech/sqle/sqle/server.(*Sqled).do(0xc00052e640, 0xc0011b6900)
	/usr/local/src/sqle/sqle/server/sqled.go:197 +0x71
github.com/actiontech/sqle/sqle/server.(*Sqled).taskLoop.func1()
	/usr/local/src/sqle/sqle/server/sqled.go:185 +0x45
created by github.com/actiontech/sqle/sqle/server.(*Sqled).taskLoop
	/usr/local/src/sqle/sqle/server/sqled.go:184 +0x16b
```

**Comment by jessun** [comment]
该问题暂未能复现
![image](https://user-images.githubusercontent.com/13587641/234792171-5666706a-b646-472c-89c3-3b92bfb32171.png)

**Comment by zhouzhilu9** [comment]
SQLE
UI Version: main dd4cb84
Server Version: main-ee 22863ca75a

1，准备测试表
![image](https://github.com/actiontech/sqle/assets/99949903/d3b3bca1-c23b-4f92-b69a-49495b82e9a7)
2，创建工单，正常审核
![image](https://github.com/actiontech/sqle/assets/99949903/68327e78-6c8b-4c82-9b45-eff9df952845)
