### ISSUE TITLE
创建审核任务组时填写的数据源名称不合规，带有空格时接口无响应

### ISSUE THREAD

**Issue by sjjian** [actiontech/sqle#1673]
## SQLe Version
sqle main

## Describe the bug

创建审核任务组时填写的数据源名称不合规，带有空格时接口无响应
### 接口
/v1/projects/{project_name}/task_groups
### 请求
场景1：请求内数据源名称带有空格
```json
{
  "instances": [
    {
      "instance_name": "test ",
      "instance_schema": "sqle"
    }
  ]
}
```
场景2：请求内数据源名称与实际数据源名称不严格匹配（即：存在大小写格式不一致）
```json
{
  "instances": [
    {
      "instance_name": "TEST",
      "instance_schema": "sqle"
    }
  ]
}
```
```bash
goroutine 9377 [running]:
net/http.(*conn).serve.func1(0xc001532140)
	/usr/local/go/src/net/http/server.go:1805 +0x153
panic(0x183d920, 0x39001b0)
	/usr/local/go/src/runtime/panic.go:971 +0x499
github.com/actiontech/sqle/sqle/api/controller/v1.CreateAuditTasksGroupV1(0x1da93b0, 0xc0015321e0, 0x0, 0x0)
	/universe/sqle/api/controller/v1/task.go:686 +0x621
github.com/actiontech/sqle/sqle/api/middleware.OperationLogRecord.func1.1(0x1da93b0, 0xc0015321e0, 0x0, 0xc00085dfb0)
	/universe/sqle/api/middleware/operation_record_ce.go:13 +0x39
github.com/actiontech/sqle/sqle/api/middleware.licenseAdapter.func1.1(0x1da93b0, 0xc0015321e0, 0x5, 0xc00040f300)
	/universe/sqle/api/middleware/license_qa.go:13 +0x39
github.com/actiontech/sqle/sqle/api/middleware.VerifyUserIsDisabled.func1.1(0x1da93b0, 0xc0015321e0, 0x4, 0x1849f80)
	/universe/sqle/api/middleware/verify_user.go:25 +0x1b2
github.com/labstack/echo/v4/middleware.JWTWithConfig.func1.1(0x1da93b0, 0xc0015321e0, 0xa, 0xc000139a20)
	/universe/vendor/github.com/labstack/echo/v4/middleware/jwt.go:238 +0x3ca
github.com/actiontech/sqle/sqle/api/middleware.JWTTokenAdapter.func1.1(0x1da93b0, 0xc0015321e0, 0x5, 0x5)
	/universe/sqle/api/middleware/jwt.go:33 +0x142
github.com/labstack/echo/v4.(*Echo).add.func1(0x1da93b0, 0xc0015321e0, 0x39600c0, 0x203000)
	/universe/vendor/github.com/labstack/echo/v4/echo.go:552 +0x62
github.com/labstack/echo/v4/middleware.LoggerWithConfig.func2.1(0x1da93b0, 0xc0015321e0, 0x0, 0x0)
	/universe/vendor/github.com/labstack/echo/v4/middleware/logger.go:117 +0x12c
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc0008fa900, 0x1d88308, 0xc0000e4000, 0xc00040f200)
	/universe/vendor/github.com/labstack/echo/v4/echo.go:662 +0x2bc
net/http.serverHandler.ServeHTTP(0xc0000e41c0, 0x1d88308, 0xc0000e4000, 0xc00040f200)
	/usr/local/go/src/net/http/server.go:2868 +0xa3
net/http.(*conn).serve(0xc001532140, 0x1d8cc00, 0xc000a20300)
	/usr/local/go/src/net/http/server.go:1933 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2994 +0x39b
```
### 预期
以上情况不会报错，只要能取到真实的数据库就可以执行。建议接口调用注意大小写。
### 原因
SQLE 业务库默认使用的字符集排序是 "utf8mb4_unicode_ci"，当输入的的数据源名称通过数据库查询数据源信息时是能匹配的，但是SQLE的业务逻辑里要求严格匹配导致了空指针

**Comment by Marcus9530** [comment]
复现版本：
UI Version: release-2.2305.x dd4cb84
Server Version: release-2.2305.x-ee 8abf46130b
复现步骤：
在swagger界面使用上述的json格式对相关接口进行请求，然后sqle出现panic

![image](https://github.com/actiontech/sqle/assets/54339501/8fcd26d5-8813-4c61-986f-4f70a406b5b8)
![image](https://github.com/actiontech/sqle/assets/54339501/33c12379-6efa-4658-b129-5f492a9f9db9)
![image](https://github.com/actiontech/sqle/assets/54339501/1be19b00-276c-4069-a21d-8cb92fe615ba)

**Comment by Marcus9530** [comment]
验证版本：Server Version: main-ee d6ade44ccf
验证步骤：
在swagger界面使用上述的json格式对相关接口进行请求，然后接口正常返回，查看std日志没有panic

![image](https://github.com/actiontech/sqle/assets/54339501/e56b0c39-d015-4bf1-bee0-ebce34948598)
![image](https://github.com/actiontech/sqle/assets/54339501/31ec3a17-c008-4d15-a277-bf13008076b2)
![image](https://github.com/actiontech/sqle/assets/54339501/8c3fad04-e08c-43eb-aa6e-ca2852f10f8f)
![image](https://github.com/actiontech/sqle/assets/54339501/bdc08a46-c902-4256-9e2c-4c697dca5426)
