### ISSUE TITLE
审核特定SQL时Panic

### ISSUE THREAD

**Issue by winfredLIN** [actiontech/sqle#1955]
#1921 在处理该问题的过程中发现
### 问题复现：
使用多表JOIN时，最后两表的连接条件使用Using，即可触发Panic

#### 例如：
SELECT * FROM table_1 JOIN table_2 on table_1.id = table_2.id JOIN table_3 USING (column_name);

```bash
goroutine 136 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x6b
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x13
github.com/actiontech/sqle/sqle/server.hookAudit.func1()
	/home/lxt/ce/sqle/sqle/server/audit.go:120 +0x4f
panic({0x24f8900?, 0xc0012ac7e0?})
	/usr/local/go/src/runtime/panic.go:920 +0x290
github.com/actiontech/sqle/sqle/driver/mysql/optimizer/index.(*Optimizer).parseSelectStmt(0xc0012ac7b0, 0xc001ad7ba0)
	/home/lxt/ce/sqle/sqle/driver/mysql/optimizer/index/optimizer.go:218 +0xc7d
github.com/actiontech/sqle/sqle/driver/mysql/optimizer/index.(*Optimizer).Optimize(0xc0012ac7b0, {0x2a6c4a8, 0x4953860}, 0xc001ad7ba0)
	/home/lxt/ce/sqle/sqle/driver/mysql/optimizer/index/optimizer.go:115 +0x86
github.com/actiontech/sqle/sqle/driver/mysql.(*MysqlDriverImpl).audit(0xc00135cd80, {0x2a6c4a8, 0x4953860}, {0xc0008e43f0, 0x63})
	/home/lxt/ce/sqle/sqle/driver/mysql/mysql.go:366 +0x10ef
github.com/actiontech/sqle/sqle/driver/mysql.(*MysqlDriverImpl).Audit(0xc00135cd80, {0x2a6c4a8, 0x4953860}, {0xc0012fceb0, 0x1, 0x1})
	/home/lxt/ce/sqle/sqle/driver/mysql/mysql.go:280 +0x29b
github.com/actiontech/sqle/sqle/server.hookAudit(0xc000593c70, 0xc001c27b00, {0x2a7d5c0, 0xc00135cd80}, {0x2a61d00, 0x4953860}, {0x4953860, 0x0, 0x0})
	/home/lxt/ce/sqle/sqle/server/audit.go:183 +0x66d
github.com/actiontech/sqle/sqle/server.audit(0xc000593c70, 0xc001c27b00, {0x2a7d5c0, 0xc00135cd80}, {0x4953860, 0x0, 0x0})
	/home/lxt/ce/sqle/sqle/server/audit.go:103 +0xa5
github.com/actiontech/sqle/sqle/server.(*action).audit(0xc001c07680)
	/home/lxt/ce/sqle/sqle/server/sqled.go:281 +0xdc
github.com/actiontech/sqle/sqle/server.(*Sqled).do(0xc0009168e0, 0xc001c07680)
	/home/lxt/ce/sqle/sqle/server/sqled.go:163 +0x65
github.com/actiontech/sqle/sqle/server.(*Sqled).taskLoop.func1()
	/home/lxt/ce/sqle/sqle/server/sqled.go:151 +0x36
created by github.com/actiontech/sqle/sqle/server.(*Sqled).taskLoop in goroutine 13
	/home/lxt/ce/sqle/sqle/server/sqled.go:150 +0x170

```

**Comment by winfredLIN** [comment]
## 解决方案
对类型断言进行断言成功与否的判断

**Comment by quexiuping** [comment]
验证完成版本：
UI Version: main 3eec557
Server Version: release-2.9999.x-ee 9f92d9b95e
