### ISSUE TITLE
查看静态审核详情panic

### ISSUE THREAD

**Issue by LordofAvernus** [actiontech/sqle#2005]
### 复现流程

任意用户登录平台并通过SQL审核功能创建一个静态审核。创建成功后切换用户【非admin】查看刚才创建的审核。出现panic信息
```
echo: http: panic serving 192.168.22.168:64876: runtime error: invalid memory address or nil pointer dereference
goroutine 775 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1850 +0x148
panic({0x246a440, 0x4765290})
	/usr/local/go/src/runtime/panic.go:890 +0x267
github.com/actiontech/sqle/sqle/api/controller/v1.checkCurrentUserCanAccessTask({0x2a21740, 0xc001333680}, 0xc0010b7e60, {0xc0018b6e08, 0x1, 0x1})
	/root/workspace/dms/sqle/sqle/api/controller/v1/project_permission.go:154 +0x227
github.com/actiontech/sqle/sqle/api/controller/v1.CheckCurrentUserCanViewTask({0x2a21740, 0xc001333680}, 0xc0010b7e60)
	/root/workspace/dms/sqle/sqle/api/controller/v1/task.go:528 +0x96
github.com/actiontech/sqle/sqle/api/controller/v2.GetTaskSQLs({0x2a21740, 0xc001333680})
	/root/workspace/dms/sqle/sqle/api/controller/v2/task.go:76 +0x238
github.com/actiontech/sqle/sqle/api/middleware.OperationLogRecord.func1.1({0x2a21740, 0xc001333680})
	/root/workspace/dms/sqle/sqle/api/middleware/operation_record_ee.go:103 +0x147
github.com/actiontech/sqle/sqle/api/middleware.licenseAdapter.func1.1({0x2a21740, 0xc001333680})
	/root/workspace/dms/sqle/sqle/api/middleware/license_qa.go:13 +0x42
github.com/actiontech/sqle/sqle/api/middleware.VerifyUserIsDisabled.func1.1({0x2a21740, 0xc001333680})
	/root/workspace/dms/sqle/sqle/api/middleware/verify_user.go:25 +0x1f0
github.com/labstack/echo/v4/middleware.JWTWithConfig.func1.1({0x2a21740, 0xc001333680})
	/root/workspace/dms/sqle/vendor/github.com/labstack/echo/v4/middleware/jwt.go:238 +0x60c
github.com/actiontech/sqle/sqle/api/middleware.JWTTokenAdapter.func1.1({0x2a21740, 0xc001333680})
	/root/workspace/dms/sqle/sqle/api/middleware/jwt.go:33 +0x3a6
github.com/labstack/echo/v4.(*Echo).add.func1({0x2a21740, 0xc001333680})
	/root/workspace/dms/sqle/vendor/github.com/labstack/echo/v4/echo.go:552 +0x88
github.com/labstack/echo/v4/middleware.LoggerWithConfig.func2.1({0x2a21740, 0xc001333680})
	/root/workspace/dms/sqle/vendor/github.com/labstack/echo/v4/middleware/logger.go:117 +0x164
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc000660fc0, {0x29f6e80, 0xc0003696c0}, 0xc000455000)
	/root/workspace/dms/sqle/vendor/github.com/labstack/echo/v4/echo.go:662 +0x2ae
net/http.serverHandler.ServeHTTP({0xc0011a21e0}, {0x29f6e80, 0xc0003696c0}, 0xc000455000)
	/usr/local/go/src/net/http/server.go:2947 +0x474
net/http.(*conn).serve(0xc0013335e0, {0x29f8110, 0xc00183ce00})
	/usr/local/go/src/net/http/server.go:1991 +0x195c
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3102 +0x9e5

```

### 问题原因
查看审核详情判断权限的流程中，通过task关联的实例来做出权限判断.静态审核未关联实例导致panic
 checkCurrentUserCanAccessTask

### 修复方案
- [x] 修复查询panic，绕过静态审核任务权限校验【v3上处理】
- [ ] #2220

**Comment by LordofAvernus** [comment]
- [ ] 修复查询panic，绕过静态审核任务权限校验【v3上已处理】
- [ ] SQL审核权限校验逻辑调整

**Comment by taolx0** [comment]
UI: main aeee2f9d
DMS: main-ee 19ee2c1ea2
SQLE: main-ee 342c635080

![20240130170715](https://github.com/actiontech/sqle/assets/63177450/cf2aae58-3a65-4e4b-93f2-72d75f840c63)
